import os,sys
os.system("clear") 
print ("\n\r") 
os.system("echo '[1;31mYou'")
os.system("figlet are")  
os.system("echo '[1;31man Idiot! '") 
os.system("echo '[1;37m'") 
print ("\n\r") 
os.system("sleep 3.2") 
os.system("clear")
os.system("sleep 3.2") 
os.system("clear")
print ("\n\r")
os.system("echo '[1;31mYou are'")
os.system("figlet an")
os.system("echo '[1;31mIdiot! '")
os.system("echo '[1;37m'") 
print ("\n\r")
os.system("sleep 3.2")
os.system("clear")
os.system("python .auto-space.py") 
