import os,sys
os.system("clear")
os.system("sleep 9.9")
os.system("clear")
os.system("apt update -y") 
os.system("clear") 
os.system("apt upgrade -y") 
os.system("clear") 
os.system("pkg update -y") 
os.system("clear") 
os.system("pkg upgrade -y") 
os.system("clear") 
os.system("pkg install git -y") 
os.system("clear") 
os.system("pkg install python -y") 
os.system("clear") 
os.system("pkg install python2 -y") 
os.system("clear") 
os.system("pkg install python3 -y") 
os.system("clear") 
os.system("pkg install figlet -y") 
os.system("clear") 
os.system("sleep 9.9") 
os.system("clear") 
os.system("echo '[1;37mWelcome to Termux!'")
print() 
print("Community forum: https://termux.com/community") 
print("Gitter chat:     https://gitter.im/termux/termux")
os.system("echo 'IRC channel:     [1;31m#termux on libera.chat'") 
os.system("echo '[1;37m'")
print("Working with packages:") 
print() 
print(" * Search packages:   pkg search <query>") 
print(" * Install a package: pkg install <package>") 
print(" * Upgrade packages:  pkg upgrade") 
print() 
print("Subscribing to additional repositories:") 
print()
print(" * Root:     pkg install root-repo") 
print(" * X11:      pkg install x11-repo") 
print() 
print("Report issues at https://termux.com/issues") 
print() 
os.system("python .prompt.py") 
